spring.application.name=tech-solution

spring.datasource.url=jdbc:postgresql://localhost:5432/tech_solution_jeiver
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080